apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: homepage
  labels:
    app: homepage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      serviceAccountName: homepage
      containers:
      - name: homepage
        image: ghcr.io/gethomepage/homepage:latest
        ports:
        - containerPort: 3000
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: LOG_TARGETS
          value: "stdout"
        - name: HOMEPAGE_ALLOWED_HOSTS
          value: "*"
        volumeMounts:
        - name: config
          mountPath: /app/config
        - name: logs
          mountPath: /app/config/logs
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          runAsNonRoot: true
      volumes:
      - name: config
        emptyDir: {}
      - name: logs
        emptyDir: {}
      initContainers:
      - name: config-init
        image: ghcr.io/gethomepage/homepage:latest
        command: ["/bin/sh", "-c"]
        args:
          - |
            cp -r /app/src/skeleton/* /app/config/ || true
            if [ ! -f /app/config/settings.yaml ]; then
              cat > /app/config/settings.yaml << 'EOF'
            ---
            title: Home Lab Dashboard
            favicon: https://github.com/walkxcode/dashboard-icons/blob/main/png/homepage.png

            theme: dark
            color: slate

            headerStyle: clean
            layout:
              Infrastructure:
                style: row
                columns: 4
              Cluster:
                style: row
                columns: 2
              Monitoring:
                style: row
                columns: 2
              "Media & Services":
                style: row
                columns: 2
            EOF
            fi
            if [ ! -f /app/config/widgets.yaml ]; then
              cat > /app/config/widgets.yaml << 'EOF'
            ---
            - resources:
                backend: resources
                expanded: true
                cpu: true
                memory: true
            - search:
                provider: duckduckgo
                target: _blank
            EOF
            fi
            if [ ! -f /app/config/services.yaml ]; then
              cat > /app/config/services.yaml << 'EOF'
            ---
            - Infrastructure:
                - Proxmox (Firefly):
                    href: https://10.10.21.31:8006/
                    description: Virtualization Platform
                    icon: proxmox
                - Ugreen NAS:
                    href: https://10.10.21.11:9443/desktop/
                    description: Network Attached Storage
                    icon: nas
                - TrueNAS:
                    href: https://10.10.21.14/ui/signin
                    description: TrueNAS Storage System
                    icon: truenas
                - PiHole:
                    href: https://10.10.21.11:18443/admin/
                    description: DNS Ad Blocker
                    icon: pihole

            - Cluster:
                - Kubernetes Dashboard:
                    href: http://10.10.21.110:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/
                    description: Kubernetes Web UI
                    icon: kubernetes
                - ArgoCD:
                    href: http://10.10.21.110:30080/
                    description: GitOps Continuous Delivery
                    icon: argocd

            - Monitoring:
                - Grafana:
                    href: http://10.10.21.110:30000
                    description: Metrics Dashboard
                    icon: grafana
                - Prometheus:
                    href: http://10.10.21.110:30003
                    description: Metrics Collection
                    icon: prometheus

            - Media & Services:
                - OctoPrint:
                    href: http://10.10.21.4
                    description: 3D Printer Management
                    icon: octoprint
                - Jellyfin:
                    href: http://10.10.21.11:8899/web/index.html
                    description: Media Server
                    icon: jellyfin
            EOF
            fi
            chown -R 1000:1000 /app/config
        volumeMounts:
        - name: config
          mountPath: /app/config
---
apiVersion: v1
kind: Service
metadata:
  name: homepage
  namespace: homepage
  labels:
    app: homepage
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001
  selector:
    app: homepage