apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: oci://8gears.container-registry.com/library/n8n
    path: .
    targetRevision: "2.0.1"
    helm:
      # Use a release name other than "n8n" so K8s does not inject N8N_PORT=tcp://... from the Service (n8n expects a number)
      releaseName: n8n-app
      valuesObject:
        # Ingress: Traefik (websecure only so TLS cert attaches to single router; HTTP→HTTPS is global in Traefik)
        ingress:
          enabled: true
          className: traefik
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
            traefik.ingress.kubernetes.io/router.tls: "true"
            traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
          hosts:
            - host: n8n.botocudo.net
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - n8n.botocudo.net
              secretName: n8n-botocudo-net-tls
        # Persistence: NFS PVC at /volume4/VM/containers/n8n/data (see storage.yaml)
        main:
          persistence:
            enabled: true
            type: existing
            existingClaim: n8n-data-pvc
          config:
            n8n:
              host: n8n.botocudo.net
              protocol: https
              # Trust X-Forwarded-* from Traefik (fixes 404 when behind reverse proxy)
              proxy_hops: 1
          # Encryption key from Secret (do not commit secrets; create n8n-secrets in namespace)
          # Chart expects extraEnv as a map (key = env name), not a list
          extraEnv:
            N8N_PORT:
              value: "5678"
            WEBHOOK_URL:
              value: "https://n8n.botocudo.net/"
            N8N_EDITOR_BASE_URL:
              value: "https://n8n.botocudo.net"
            N8N_ENCRYPTION_KEY:
              valueFrom:
                secretKeyRef:
                  name: n8n-secrets
                  key: encryption-key
            N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS:
              value: "true"
            # Deprecation / future defaults (see n8n docs)
            DB_SQLITE_POOL_SIZE:
              value: "1"
            N8N_RUNNERS_ENABLED:
              value: "true"
            N8N_BLOCK_ENV_ACCESS_IN_NODE:
              value: "false"
            N8N_GIT_NODE_DISABLE_BARE_REPOS:
              value: "true"
          # Force N8N_PORT=5678 so K8s-injected N8N_PORT=tcp://... (from Service "n8n") is overridden at runtime
          command:
            - /bin/sh
            - -c
            - "export N8N_PORT=5678; exec /docker-entrypoint.sh"
          # Ensure NFS data dir is writable by n8n (UID 1000); avoids exit 1 from permission denied
          initContainers:
            - name: fix-data-permissions
              image: busybox:1.36
              command: ["/bin/sh", "-c", "mkdir -p /home/node/.n8n && chown -R 1000:1000 /home/node/.n8n && chmod -R 755 /home/node/.n8n"]
              volumeMounts:
                - name: data
                  mountPath: /home/node/.n8n
              securityContext:
                runAsUser: 0
          # Give n8n time to start and bind to 5678 before first probe (avoids connection refused)
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 120
            periodSeconds: 10
            failureThreshold: 9
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 180
            periodSeconds: 15
            failureThreshold: 6
  destination:
    server: https://kubernetes.default.svc
    namespace: n8n
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
