# Deploys n8n namespace and NFS PV/PVC only. Apply before or with n8n-app.yaml.
# n8n-app.yaml (Helm) uses the PVC via main.persistence.existingClaim.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n-storage
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/fafiorim/homelab
    targetRevision: main
    path: proxmox-talos/apps/n8n
  destination:
    server: https://kubernetes.default.svc
    namespace: n8n
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
