apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: oci://8gears.container-registry.com/library/n8n
    path: .
    targetRevision: "2.0.1"
    helm:
      releaseName: n8n
      valuesObject:
        # Ingress: Traefik (websecure only so TLS cert attaches to single router; HTTP→HTTPS is global in Traefik)
        ingress:
          enabled: true
          className: traefik
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
            traefik.ingress.kubernetes.io/router.tls: "true"
            traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
          hosts:
            - host: n8n.botocudo.net
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - n8n.botocudo.net
              secretName: n8n-botocudo-net-tls
        # Persistence: NFS PVC at /volume4/VM/containers/n8n/data (see storage.yaml)
        main:
          persistence:
            enabled: true
            type: existing
            existingClaim: n8n-data-pvc
          config:
            n8n:
              host: n8n.botocudo.net
              protocol: https
              # Trust X-Forwarded-* from Traefik (fixes 404 when behind reverse proxy)
              proxy_hops: 1
          # Encryption key from Secret (do not commit secrets; create n8n-secrets in namespace)
          extraEnv:
            - name: WEBHOOK_URL
              value: "https://n8n.botocudo.net/"
            - name: N8N_EDITOR_BASE_URL
              value: "https://n8n.botocudo.net"
            - name: N8N_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: n8n-secrets
                  key: encryption-key
          # Give n8n time to start before probes (avoids BackOff / connection refused on :5678)
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 90
            periodSeconds: 15
            failureThreshold: 6
  destination:
    server: https://kubernetes.default.svc
    namespace: n8n
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
