apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: traefik-system
data:
  traefik.yml: |
    api:
      dashboard: true
      insecure: true

    entryPoints:
      web:
        address: ":80"
        http:
          redirections:
            entrypoint:
              to: websecure
              scheme: https
      websecure:
        address: ":443"
      traefik:
        address: ":8080"

    certificatesResolvers:
      letsencrypt:
        acme:
          email: franz@vitorf.com
          storage: /data/acme.json
          httpChallenge:
            entryPoint: web
      letsencrypt-staging:
        acme:
          email: franz@vitorf.com
          storage: /data/acme-staging.json
          caServer: https://acme-staging-v02.api.letsencrypt.org/directory
          httpChallenge:
            entryPoint: web

    providers:
      kubernetesIngress:
        ingressClass: traefik
      kubernetesCRD: {}

    # Enhanced Access Logging with structured format
    accessLog:
      format: json
      fields:
        names:
          StartUTC: drop
        headers:
          defaultMode: keep
          names:
            User-Agent: redact
            Authorization: drop
            Content-Type: keep

    # Prometheus Metrics
    metrics:
      prometheus:
        addEntryPointsLabels: true
        addServicesLabels: true
        addRoutersLabels: true
        buckets:
          - 0.1
          - 0.3
          - 1.2
          - 5.0

    # Global configuration
    global:
      checkNewVersion: false
      sendAnonymousUsage: false

    # Health check endpoint
    ping:
      entryPoint: traefik