apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-proxy-manager
  namespace: argocd
  labels:
    app.kubernetes.io/name: nginx-proxy-manager
    app.kubernetes.io/part-of: network-infrastructure
spec:
  project: default
  source:
    repoURL: https://github.com/fafiorim/homelab.git
    targetRevision: HEAD
    path: proxmox-talos/apps/nginx-proxy-manager
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-proxy-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true