---
# ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: homepage
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
secrets:
  - name: homepage

---
# Secret for ServiceAccount
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: homepage
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
  annotations:
    kubernetes.io/service-account.name: homepage

---
# ConfigMap for Homepage configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: "Lab Dashboard"
    background: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
    cardBlur: md
    theme: dark
    color: slate
    headerStyle: boxed
    hideVersion: true
    layout:
      - Infrastructure:
          style: row
          columns: 3
      - Media Services:
          style: row  
          columns: 2
      - Network & Security:
          style: row
          columns: 2
      - Kubernetes Management:
          style: row
          columns: 4
    language: en
    startUrl: /
    useEqualHeights: true
    quicklaunch:
      searchDescriptions: true
      hideInternetSearch: false
      hideVisitURL: false
  custom.css: ""
  bookmarks.yaml: |
    - Development:
        - GitHub:
            - abbr: GH
              href: https://github.com/fafiorim
              icon: github.png
        - GitLab:
            - abbr: GL
              href: https://gitlab.com/
              icon: gitlab.png
        - Docker Hub:
            - abbr: DH
              href: https://hub.docker.com/
              icon: docker.png
    
    - Cloud & Infrastructure:
        - Proxmox:
            - abbr: PVE
              href: https://10.10.21.100:8006
              icon: proxmox.png
        - Talos Dashboard:
            - abbr: TAL
              href: https://www.talos.dev/
              icon: talos.png
    
    - Documentation:
        - Kubernetes Docs:
            - abbr: K8s
              href: https://kubernetes.io/docs/
              icon: kubernetes.png
        - Homepage Docs:
            - abbr: HP
              href: https://gethomepage.dev/
              icon: homepage.png
        - Talos Documentation:
            - abbr: DOC
              href: https://www.talos.dev/docs/
              icon: talos.png
  
  services.yaml: |
    - Infrastructure:
        - Proxmox Node 1:
            href: https://10.10.21.100:8006
            description: Primary hypervisor
            icon: proxmox.png
        
        - Proxmox Node 2:
            href: https://10.10.21.101:8006
            description: Secondary hypervisor
            icon: proxmox.png
    
    - Media Services:
        - Jellyfin:
            href: https://jellyfin.yourdomain.com
            description: Media streaming server
            icon: jellyfin.png
    
    - Network & Security:
        - Pi-hole:
            href: http://10.10.21.50/admin
            description: Network-wide ad blocker
            icon: pihole.png
    
    - Kubernetes Management:
        - Homepage Dashboard:
            href: http://10.10.21.200:30090
            description: This dashboard
            icon: homepage.png
            
        - Cluster Overview:
            href: "#"
            description: Kubernetes cluster status
            icon: kubernetes.png
  
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "Production Cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        disk: /
    
    - search:
        provider: duckduckgo
        target: _blank
    
    - datetime:
        text_size: xl
        format:
          timeStyle: short
          dateStyle: short
          hourCycle: h23

---
# ClusterRole for Kubernetes API access
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods
      - nodes
    verbs:
      - get
      - list
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
  - apiGroups:
      - traefik.containo.us
      - traefik.io
    resources:
      - ingressroutes
    verbs:
      - get
      - list
  - apiGroups:
      - metrics.k8s.io
    resources:
      - nodes
      - pods
    verbs:
      - get
      - list
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions/status
    verbs:
      - get

---
# ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: homepage
subjects:
  - kind: ServiceAccount
    name: homepage
    namespace: default

---
# Service - ClusterIP
apiVersion: v1
kind: Service
metadata:
  name: homepage
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: homepage

---
# Service - NodePort
apiVersion: v1
kind: Service
metadata:
  name: homepage-nodeport
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      nodePort: 30090
  selector:
    app.kubernetes.io/name: homepage

---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: homepage
  template:
    metadata:
      labels:
        app.kubernetes.io/name: homepage
    spec:
      serviceAccountName: homepage
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: homepage
          image: "ghcr.io/gethomepage/homepage:latest"
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
          env:
            - name: HOMEPAGE_ALLOWED_HOSTS
              value: "localhost:3000,10.10.21.200:30090,10.10.21.211:30090,10.10.21.212:30090"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /app/config/custom.css
              name: homepage-config
              subPath: custom.css
            - mountPath: /app/config/bookmarks.yaml
              name: homepage-config
              subPath: bookmarks.yaml
            - mountPath: /app/config/kubernetes.yaml
              name: homepage-config
              subPath: kubernetes.yaml
            - mountPath: /app/config/services.yaml
              name: homepage-config
              subPath: services.yaml
            - mountPath: /app/config/settings.yaml
              name: homepage-config
              subPath: settings.yaml
            - mountPath: /app/config/widgets.yaml
              name: homepage-config
              subPath: widgets.yaml
            - mountPath: /app/config/logs
              name: logs
          livenessProbe:
            httpGet:
              path: /api/healthz
              port: http
            initialDelaySeconds: 30
            failureThreshold: 3
            timeoutSeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/healthz
              port: http
            initialDelaySeconds: 5
            failureThreshold: 3
            timeoutSeconds: 5
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /api/healthz
              port: http
            initialDelaySeconds: 10
            failureThreshold: 30
            timeoutSeconds: 5
            periodSeconds: 5
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
      volumes:
        - name: homepage-config
          configMap:
            name: homepage
        - name: logs
          emptyDir: {}