---
apiVersion: v1
kind: Service
metadata:
  name: homepage-loadbalancer
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
    app.kubernetes.io/component: loadbalancer
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: homepage
