apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - rbac.yaml
  - prometheus.yaml
  - grafana.yaml
  - node-exporter.yaml

namespace: monitoring

commonLabels:
  app.kubernetes.io/part-of: monitoring-stack