apiVersion: v1
kind: PersistentVolume
metadata:
  name: uptime-kuma-data-pv
  labels:
    app: uptime-kuma
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /volume4/VM/containers/uptime-kuma/data
    server: 10.10.21.11
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma-data-pvc
  namespace: uptime-kuma
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 5Gi
