apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-server
  namespace: immich
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-server
  template:
    metadata:
      labels:
        app: immich-server
        app.kubernetes.io/part-of: immich-stack
    spec:
      containers:
      - name: immich-server
        image: ghcr.io/immich-app/immich-server:v2.5.5
        ports:
        - containerPort: 2283
        env:
        - name: DB_HOSTNAME
          value: "immich-postgres"
        - name: DB_USERNAME
          value: "immich"
        - name: DB_PASSWORD
          value: "immich"
        - name: DB_DATABASE_NAME
          value: "immich"
        - name: REDIS_HOSTNAME
          value: "immich-redis"
        - name: UPLOAD_LOCATION
          value: "/usr/src/app/upload"
        resources:
          requests:
            memory: "1Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "6000m"
        volumeMounts:
        - name: upload
          mountPath: /usr/src/app/upload
        - name: library
          mountPath: /usr/src/app/library
      volumes:
      - name: upload
        persistentVolumeClaim:
          claimName: immich-upload-pvc
      - name: library
        persistentVolumeClaim:
          claimName: immich-library-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: immich-server
  namespace: immich
spec:
  selector:
    app: immich-server
  ports:
  - port: 2283
    targetPort: 2283
