apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/fafiorim/homelab
    targetRevision: main
    path: proxmox-talos/apps/immich
  destination:
    server: https://kubernetes.default.svc
    namespace: immich
  # Ignore immutable fields: PVC volumeName (set when bound), Deployment selector (immutable)
  ignoreDifferences:
    - group: ""
      kind: PersistentVolumeClaim
      jqPathExpressions:
        - .spec.volumeName
    - group: apps
      kind: Deployment
      jqPathExpressions:
        - .spec.selector
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
