# Homepage Bookmarks Configuration
# Edit this file to modify the quick access bookmarks

- Development:
    - GitHub:
        - abbr: GH
          href: https://github.com/fafiorim
          icon: github.png
    - GitLab:
        - abbr: GL
          href: https://gitlab.com/
          icon: gitlab.png
    - Docker Hub:
        - abbr: DH
          href: https://hub.docker.com/
          icon: docker.png

- Cloud & Infrastructure:
    - Proxmox:
        - abbr: PVE
          href: https://10.10.21.100:8006
          icon: proxmox.png
    - Talos Dashboard:
        - abbr: TAL
          href: https://www.talos.dev/
          icon: talos.png

- Documentation:
    - Kubernetes Docs:
        - abbr: K8s
          href: https://kubernetes.io/docs/
          icon: kubernetes.png
    - Homepage Docs:
        - abbr: HP
          href: https://gethomepage.dev/
          icon: homepage.png
    - Talos Documentation:
        - abbr: DOC
          href: https://www.talos.dev/docs/
          icon: talos.png

- Monitoring:
    - Homepage Widgets:
        - abbr: WID
          href: https://gethomepage.dev/widgets/
          icon: homepage.png