# Homepage Services Configuration
# Edit this file to add/modify services shown in your dashboard

- Infrastructure:
    - Proxmox Firefly:
        href: https://10.10.21.100:8006
        description: Primary hypervisor node
        icon: proxmox.png
        # Uncomment and configure widget when ready:
        # widget:
        #   type: proxmox
        #   url: https://10.10.21.100:8006
        #   username: homepage@pam
        #   password: your-password-or-token

    - Proxmox DragonFly:
        href: https://10.10.21.101:8006
        description: Secondary hypervisor node
        icon: proxmox.png

    - TrueNAS:
        href: https://10.10.21.102
        description: Network attached storage
        icon: truenas.png
        # Uncomment and configure widget when ready:
        # widget:
        #   type: truenas
        #   url: https://10.10.21.102
        #   username: homepage
        #   password: your-truenas-password

    - Ugreen NAS:
        href: https://10.10.21.103
        description: Secondary NAS storage
        icon: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQd7otD4AEZ_Z-Ec3bQimBfnL0mok5yorbGdlDRrRVQaEFkZET_qJInRE4LiCu5qvkoIrA&usqp=CAU

- Media Services:
    - Jellyfin:
        href: https://10.10.21.104:8096
        description: Media streaming server
        icon: jellyfin.png
        # Uncomment and configure widget when ready:
        # widget:
        #   type: jellyfin
        #   url: https://10.10.21.104:8096
        #   key: your-jellyfin-api-key
        #   enableBlocks: true
        #   enableNowPlaying: true

- Network & Security:
    - Pi-hole:
        href: http://10.10.21.50/admin
        description: Network-wide ad blocker
        icon: pi-hole.png
        # Uncomment and configure widget when ready:
        # widget:
        #   type: pihole
        #   url: http://10.10.21.50
        #   key: your-pihole-api-key

- Kubernetes Management:
    - Homepage Dashboard:
        href: http://10.10.21.200:30090
        description: This dashboard
        icon: homepage.png
        
    - Cluster Overview:
        href: "#"
        description: Kubernetes cluster status
        icon: kubernetes.png

# To add a new service:
# 1. Copy an existing service block
# 2. Update the href, description, and icon
# 3. Configure the widget if supported
# 4. Commit and push to deploy automatically