# Homepage Widgets Configuration
# Edit this file to modify the widgets displayed at the top of your dashboard

- kubernetes:
    cluster:
      show: true
      cpu: true
      memory: true
      showLabel: true
      label: "Production Cluster"
    nodes:
      show: true
      cpu: true
      memory: true
      showLabel: true

- resources:
    backend: resources
    expanded: true
    cpu: true
    memory: true
    disk: /

- search:
    provider: duckduckgo
    target: _blank

- datetime:
    text_size: xl
    format:
      timeStyle: short
      dateStyle: short
      hourCycle: h23

# Uncomment to add weather widget:
# - openweathermap:
#     latitude: 40.7128
#     longitude: -74.0060
#     provider: openweathermap
#     apikey: your-openweather-api-key
#     units: metric

# Note: If you're getting metrics errors, comment out the kubernetes and resources widgets above
# and uncomment the simplified version below:

# - search:
#     provider: duckduckgo
#     target: _blank

# - datetime:
#     text_size: xl
#     format:
#       timeStyle: short
#       dateStyle: short
#       hourCycle: h23