apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  labels:
    app.kubernetes.io/name: metallb
    app.kubernetes.io/part-of: network-infrastructure
spec:
  project: default
  source:
    repoURL: https://github.com/fafiorim/homelab.git
    targetRevision: HEAD
    path: proxmox-talos/apps/metallb
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true