apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperless
  namespace: paperless
  labels:
    app: paperless
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paperless
  template:
    metadata:
      labels:
        app: paperless
    spec:
      initContainers:
      - name: wait-for-redis
        image: busybox:1.36
        command: ['sh', '-c', 'until nc -z redis 6379; do echo waiting for redis; sleep 2; done']
      - name: wait-for-postgresql
        image: busybox:1.36
        command: ['sh', '-c', 'until nc -z postgresql 5432; do echo waiting for postgresql; sleep 2; done']
      containers:
      - name: paperless
        image: ghcr.io/paperless-ngx/paperless-ngx:latest
        ports:
        - containerPort: 8000
        env:
        - name: PAPERLESS_REDIS
          value: "redis://redis:6379"
        - name: PAPERLESS_DBENGINE
          value: "postgresql"
        - name: PAPERLESS_DBHOST
          value: "postgresql"
        - name: PAPERLESS_DBPORT
          value: "5432"
        - name: PAPERLESS_DBNAME
          value: "paperless"
        - name: PAPERLESS_DBUSER
          value: "paperless"
        - name: PAPERLESS_DBPASS
          value: "paperless"
        - name: PAPERLESS_SECRET_KEY
          value: "change-me-to-a-random-string"
        - name: PAPERLESS_URL
          value: "https://paperless.botocudo.net"
        - name: PAPERLESS_TIME_ZONE
          value: "UTC"
        - name: PAPERLESS_OCR_LANGUAGE
          value: "eng"
        - name: PAPERLESS_ADMIN_USER
          value: "admin"
        - name: PAPERLESS_ADMIN_PASSWORD
          value: "admin123"
        - name: PAPERLESS_ADMIN_MAIL
          value: "admin@botocudo.net"
        - name: USERMAP_UID
          value: "1000"
        - name: USERMAP_GID
          value: "1000"
        - name: PAPERLESS_PORT
          value: "8000"
        volumeMounts:
        - name: data
          mountPath: /usr/src/paperless/data
        - name: media
          mountPath: /usr/src/paperless/media
        - name: consume
          mountPath: /usr/src/paperless/consume
        - name: export
          mountPath: /usr/src/paperless/export
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
      volumes:
      - name: data
        hostPath:
          path: /var/mnt/paperless/data
          type: DirectoryOrCreate
      - name: media
        hostPath:
          path: /var/mnt/paperless/media
          type: DirectoryOrCreate
      - name: consume
        hostPath:
          path: /var/mnt/paperless/consume
          type: DirectoryOrCreate
      - name: export
        hostPath:
          path: /var/mnt/paperless/export
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: paperless
  namespace: paperless
  labels:
    app: paperless
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: paperless
