apiVersion: v1
kind: Service
metadata:
  name: traefik-hostnetwork
  namespace: traefik-system
  labels:
    app: traefik
spec:
  type: ClusterIP
  clusterIP: None  # Headless service for direct node access
  selector:
    app: traefik
  ports:
    - name: web
      port: 80
      targetPort: 80
    - name: websecure
      port: 443
      targetPort: 443
    - name: admin
      port: 8080
      targetPort: 8080