apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/part-of: network-infrastructure
spec:
  project: default
  source:
    repoURL: https://github.com/fafiorim/homelab.git
    targetRevision: HEAD
    path: proxmox-talos/apps/traefik
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true