apiVersion: v1
kind: Namespace
metadata:
  name: simple-test
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: simple-config
  namespace: simple-test
data:
  message: "Hello from ArgoCD!"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deployment
  namespace: simple-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-test
  template:
    metadata:
      labels:
        app: simple-test
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: simple-service
  namespace: simple-test
spec:
  selector:
    app: simple-test
  ports:
  - port: 80
    targetPort: 80
  type: NodePort
