apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy-manager
  namespace: nginx-proxy-manager
  labels:
    app: nginx-proxy-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-proxy-manager
  template:
    metadata:
      labels:
        app: nginx-proxy-manager
    spec:
      containers:
        - name: nginx-proxy-manager
          image: jc21/nginx-proxy-manager:2.10.4
          ports:
            - containerPort: 80
              name: http
            - containerPort: 443
              name: https
            - containerPort: 81
              name: admin
          env:
            - name: DISABLE_IPV6
              value: "true"
            - name: NPM_ADMIN_USER
              value: "admin@example.com"
            - name: NPM_ADMIN_PASS
              value: "changeme"
          volumeMounts:
            - name: data
              mountPath: /data
            - name: letsencrypt
              mountPath: /etc/letsencrypt
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          securityContext:
            runAsUser: 0
            runAsGroup: 0
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: nginx-proxy-manager-data
        - name: letsencrypt
          persistentVolumeClaim:
            claimName: nginx-proxy-manager-letsencrypt
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy-manager
  namespace: nginx-proxy-manager
  labels:
    app: nginx-proxy-manager
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      name: http
    - port: 443
      targetPort: 443
      name: https
    - port: 81
      targetPort: 81
      name: admin
  selector:
    app: nginx-proxy-manager