apiVersion: v1
kind: PersistentVolume
metadata:
  name: open-webui-data-pv
  labels:
    app: open-webui
    volume: data
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 10.10.21.11
    path: /volume4/VM/containers/open-webui/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui-data-pvc
  namespace: open-webui
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: open-webui
      volume: data
