apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/name: arc-controller
    app.kubernetes.io/part-of: github-actions-runners
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller
    path: .
    targetRevision: "0.14.1"
    helm:
      releaseName: arc
      valuesObject:
        flags:
          logLevel: info
          logFormat: text
          runnerMaxConcurrentReconciles: 6
          excludeLabelPropagationPrefixes:
            - argocd.argoproj.io/instance
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: arc-systems
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
